version: "3.8"

services:
  backend:
    build: ./order_backend
    ports:
      - "8000:8000"
    volumes:
      - ./order_backend:/app
    restart: always
    environment:
      - DATABASE_URL=sqlite:///./orders.db

  frontend:
    build: ./order_frontend
    ports:
      - "3000:3000"  # Changed from 3000:80
    depends_on:
      - backend
    restart: always